### ISSUE TITLE
Choosing a device out of .list() doesn't work - "cannot move out of borrowed content"

### ISSUE THREAD

**Issue by h4sh5** [ebfull/pcap#100]
```
fn start_capture(index: usize) -> () {
    let devices = pcap::Device::list().unwrap();
    let chosen = devices.iter().nth(index).unwrap();//last unwrap gets rid of Option
    println!("Chosen {:#?}:", chosen);
    let mut cap = chosen.open();
}
```

When compiling this rust complaines on the chosen.open() line saying "cannot move out of borrowed content". Why is this so? Shouldn't open() take a reference to self (&self) instead of taking ownership (self)? 

I am trying to let the user select an interface from the existing list and capture on that.

**Comment by packysauce** [comment]
Looks like you'd probably want to use `Vec::remove()`, it takes an index and returns the object from that position as an owned one.

Here's your snippet with my modifications
```
fn start_capture(index: usize) -> () {
  let mut devices = pcap::Device::list().unwrap();  // devices needs to be mutable, since we're stealing from it
  let chosen = devices.remove(index);  // no bounds checking though, be careful!
  println!("Chosen {:#?}:", chosen);
  let mut cap = chosen.open();
}
```

**Comment by sekineh** [comment]
Another workaround is to use `Capture::from_device(device_list[3].name.as_ref())` like below.

```
    let device_list = Device::list()?;
    for (i, d) in device_list.iter().enumerate() {
        println!("{} = {:?}", i, d);
    }
    // let _ = Capture::from_device(device)
    // let device = Device::open()?;
    // let device = Device::from(device_list[0].name.as_ref());
    // println!("device = {:?}", device);
    // let mut cap = device.open()?;
    let mut cap = Capture::from_device(device_list[3].name.as_ref())?
        .promisc(true)
        .snaplen(64)
        .open()?;

    if let Ok(packet) = cap.next() {
        println!("received packet! {:?}", packet);
    }
```

**Comment by sekineh** [comment]
Add `derive(Clone)` to `struct Device` might increase usability.

**Comment by Wojtek242** [comment]
Does this need fixing within `pcap` itself or are the solutions provided sufficient (in which case the issue can be close)?

**Comment by sekineh** [comment]
> Does this need fixing within `pcap` itself or are the solutions provided sufficient (in which case the issue can be close)?

It's an ergonomistic issue and I'd like to investigate.
