### ISSUE TITLE
capture.next() seems to wait forever on FreeBSD 11

### ISSUE THREAD

**Issue by SoloSteve** [ebfull/pcap#103]
I have a simple program that I'm compiling on FreeBSD 11.2

```
use pcap;

fn main() {
        println!("{:?}", pcap::Device::list());
        let mut capture = pcap::Capture::from_device("em0").unwrap().open().unwrap();
        capture.next();
        println!("Done");
}
```
The program seems to just wait on `capture.next()`.

- The line `pcap::Device::list()` does work.
- tcpdump works
- Programs written in C that use pcap and are compiled in clang do work.

What could be the problem?

**Comment by tnull** [comment]
Maybe this is the same issue as #93 ?

**Comment by sekineh** [comment]
This is not a bug, you should set timeout other than 0:
https://docs.rs/pcap/0.7.0/pcap/struct.Capture.html#method.timeout

If you don't set timeout value, it will block forever.

**Comment by sekineh** [comment]
`capture.next()` should block until packet arrives or timeout expires.  By default, timeout never expires and wait forever.

We might need better guidance, though.  Maybe add timeout to examples?
