### ISSUE TITLE
Read packet data and send packet to device/IP on interface

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [ebfull/pcap#104]
I have supposedly figured out how to send a packet, like so:
https://bin.privacytools.io/?8836d50df4eeb1ed#a4JT9nbu8ZJndVs7E71D7V1DhhbLTBltBtQhOBOfmPc=

Reading packages from the interface like so:
```
        while let Ok(packet) = cap.next() {
                println!("received packet! {:?}", packet);
        }
```

But, how do I filter the packet.data for a specific IP addr/MAC addr? How do I extract that from the packet?
Let alone, how do I filter/see it's Protocol and it's Data?

Can I send packets to a specific IP addr/MAC addr on that interface?

I can't figure it out form the documentation myself.

Bonus question:
Can I send and read at the same time with only one 'Capture::from_device'?

**Comment by Wojtek242** [comment]
> But, how do I filter the packet.data for a specific IP addr/MAC addr? How do I extract that from the packet?

You can use the [`filter`](https://docs.rs/pcap/0.7.0/pcap/struct.Capture.html#method.filter) function. See the [`listenlocalhost` example](https://github.com/ebfull/pcap/blob/812ab902a6ab5b4905a03ede0bc39fbdff534d2b/examples/listenlocalhost.rs). The filter syntax can be found at https://biot.com/capstats/bpf.html.

> Let alone, how do I filter/see it's Protocol and it's Data?

For filtering, see above. For seeing, I believe that you would have to parse the packet's bytes yourself to see its contents.

> Can I send packets to a specific IP addr/MAC addr on that interface?

Yes, if you construct a valid packet with headers that specify those IP address/Mac address in its headers.

> Can I send and read at the same time with only one 'Capture::from_device'?

I believe you can and I'm pretty sure I've already tried it, but I don't have examples to point to.

**Comment by Wojtek242** [comment]
Since this issue is over a year old, I will close it, but please feel free to re-open it if the answers are not sufficient and you have more questions!
