### ISSUE TITLE
Packet header/data lifetimes

### ISSUE THREAD

**Issue by tomaszjonak** [ebfull/pcap#107]
I've been toying with iterator trait implementation on capture<active>. While trying to get lifetimes right I've started digging in what packet header and data fields are pointing at.

Judging from source: 
https://github.com/ebfull/pcap/blob/99c328a6dd468ad8ec514280aa185843d307e11e/src/lib.rs#L263-L268
https://github.com/ebfull/pcap/blob/99c328a6dd468ad8ec514280aa185843d307e11e/src/lib.rs#L648-L658
they are directly referring to memory managed by pcap_next_ex. Manpage for this call states that
> The packet data is not to be freed by the caller, and is not guaranteed to be valid after the next call to pcap_next_ex(), pcap_next(), pcap_loop(), or pcap_dispatch(); if the code needs it to remain valid, it must make a copy of it.

If I understand correctly this may lead to some memory issues if somebody stores packets for processing.

**Comment by sekineh** [comment]
> > An easy solution is to add a documentation for this limitation.
> 
> Please consider marking it as unsafe - Many devs don't have the time to read the entire documentation, and expect that a safe function is safe :)

We might need both `unsafe` and documentation :-)
Developers will need to know the requirement `unsafe` means.

> 
> If next would take a &mut self, would the second borrow be forbidden?

Currently `next()` takes `&mut self` and you can call it twice or more.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b75b62a9f86c723934248b1ff78fc588

**Comment by Trolldemorted** [comment]
>Currently next() takes &mut self and you can call it twice or more.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b75b62a9f86c723934248b1ff78fc588

You can call next twice in your example because it does not return a reference. If you [return a reference instead](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9831d265c36e6ecd4e997686c950a835) you get the expected `cannot borrow `s` as mutable more than once at a time` message.

**Comment by sekineh** [comment]
I think the reported problem is prevented by the compiler.

## Compiler catches second call of `next()`.

```
use pcap::Device;

fn main() {
    let mut cap = Device::lookup().unwrap().open().unwrap();
    let a = cap.next();
    let b = cap.next();
    dbg!(a, b); // use a and b here
}
```
produces the following error:
```
$ cargo build
   Compiling pcap107 v0.1.0 (C:\workt480\05RustLang\pcap107)                                                                                                       
error[E0499]: cannot borrow `cap` as mutable more than once at a time
 --> src\main.rs:6:13
  |
5 |     let a = cap.next();
  |             --- first mutable borrow occurs here
6 |     let b = cap.next();
  |             ^^^ second mutable borrow occurs here
7 |     dbg!(a, b); // use a and b here
  |          - first borrow later used here
```

**Comment by sekineh** [comment]
```
 pub fn next(&mut self) -> Result<Packet, Error> { 
```
is actually
```
 pub fn next(&'a mut self) -> Result<Packet<'a>, Error> { 
```

In which the returned value `Packet<'a>` can't outlive the mutable borrow of `&mut self`.
It will prevent memory issues.
