### ISSUE TITLE
has anyone tried Fuchsia kernel packet driver mechanisms?

### ISSUE THREAD

**Issue by naturallymitchell** [ebfull/pcap#109]
https://github.com/vsrinivas/fuchsia/search?l=C&q=ethernet+driver
https://github.com/vsrinivas/fuchsia/search?l=C&q=monitor+mode

**Comment by sekineh** [comment]
Does fuchsia has a `libpcap` port?

If yes, it's feasible to use this crate.
If no, I think you have to write equivalent of the `libpcap` first.

**Comment by sekineh** [comment]
Currently fuchsia platform is not supported.
