### ISSUE TITLE
All from_raw_fd foo must be unsafe

### ISSUE THREAD

**Issue by Trolldemorted** [ebfull/pcap#127]
As #119 and git blame have shown, even core devs cannot handle handle the unsafety 😛

Seriously, using them is unsafe and should be declared as such.

**Comment by sekineh** [comment]
I agree.

We might want to implement `FramRawFd` trait which forces `unsafe fn from_raw_fd(fd: RawFd) -> Self` interface.
https://doc.rust-lang.org/std/fs/struct.File.html#impl-FromRawFd
