### ISSUE TITLE
Pick working Minimum Supported Rustc Version

### ISSUE THREAD

**Issue by sekineh** [ebfull/pcap#130]
I tried 1.31.1 in the CI and unfortunately the build failed.
Result: https://github.com/ebfull/pcap/runs/1064490417

I feel backporting to the old compiler a bit counter-productive.

TODO:
- Pick the version we like to support (just picking the latest stable is OK, in my opinion)
- add GitHub Actions matrix for the version we chose.
- update the `README` which mentions `1.31`

Any opinions?

**Comment by Trolldemorted** [comment]
Is building with old rustc versions something you want to support? I'd say as long as it builds with the latest stable, beta and nightly it is fine

**Comment by sekineh** [comment]
I think 1.31 is too old, but users don't update rustc very often.
I'd like to support at least the current `stable` (1.46?) for the time being.
This will prevent sudden breakage on user side.

**Comment by Wojtek242** [comment]
Weren't editions meant to solve problems like this? 

I wouldn't get too hung up on ensuring support for older versions of the compiler as long as stable is supported, but knowing which is the oldest version that still compiles and runs would be helpful to have in the README. Having it in CI would also be helpful to know when that needs to be updated. I guess we just need to do a binary search to figure out the version.

**Comment by sekineh** [comment]
> Weren't editions meant to solve problems like this?

Between two editions (2018 and upcoming? 2021), many new features are added.  If we use those new features, some people will encounter a build ffailure.

> I wouldn't get too hung up on ensuring support for older versions of the compiler as long as stable is supported, but knowing which is the oldest version that still compiles and runs would be helpful to have in the README. Having it in CI would also be helpful to know when that needs to be updated. I guess we just need to do a binary search to figure out the version.

Sounds reasonable.
I'll try several versions and pick that version as minimum without precise binary-search.
I'll make the PR# for that!
