### ISSUE TITLE
Build-time `pcap_lib_version` probe

### ISSUE THREAD

**Issue by sekineh** [ebfull/pcap#136]
It might be useful for linux / macos platforms. (automatically include `libpcap` version-dependent features)

Similar to:
https://github.com/Wojtek242/pcap/pull/3/files

**Comment by sekineh** [comment]
I set `v0.8.0` milestone for now, assuming @Wojtek242 is eager to implement this.

**Comment by sekineh** [comment]
Note:
In `npcap`, `pcap_lib_version()` probabry returns "1.9.x" or something, but they don't have `*fopen*` functions exported.
They have `*hopen*` functions instead.

See the link:
- https://gist.github.com/sekineh/31a6887ddca0ddf5b551e70436e2764d#gistcomment-3450129

Hmm, we still need `cfg(windows)` even after we implement version probe?

**Comment by Wojtek242** [comment]
> Hmm, we still need `cfg(windows)` even after we implement version probe?

Sadly, that was always the case. For some reason the windows pcap library just does some things its own way. I don't think there is any way to avoid this.

**Comment by Wojtek242** [comment]
> I set `v0.8.0` milestone for now, assuming @Wojtek242 is eager to implement this.

Yes, I will simply port the code from my fork. But let us decide first if we want `build.rs` or featurs in #118.

**Comment by Wojtek242** [comment]
Resolved by #138
