### ISSUE TITLE
Consistent code formatting

### ISSUE THREAD

**Issue by Wojtek242** [ebfull/pcap#142]
Basically, just run `rustfmt` on the code as long as we agree on the settings. I propose to start with the default and go from there.

Also needs to be added to CI to ensure new PRs don't break formatting.

**Comment by Wojtek242** [comment]
Best to leave this one as the last issue before 0.8.0 as otherwise it will create conflicts with existing PRs some of which we might want to merge.

**Comment by Stargateur** [comment]
I strongly support this, it's really annoying to work on a project where you can't rustfmt, that say I have no problem to have a rustfmt.toml to configure it as owner please
