### ISSUE TITLE
Device::lookup panics on windows 10

### ISSUE THREAD

**Issue by sigmaSd** [ebfull/pcap#150]
Hi, I tried pcap on windows with the latest fix   https://github.com/ebfull/pcap/commit/8c4fed5c7c296b5ff01516ada31ce2b7052887bf

but now  `Device::lookup().unwrap()` fails with a diffrent error

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PcapError("PacketGetAdapterNames: The data area passed to a system call is too small. (122)")', src\ip.rs:19:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sigmaSd** [comment]
I think its due to using cmd without admin previlege.

With admin it doesnt panic, but no packets are detected, but I'll have to debug that.

**Comment by sigmaSd** [comment]
Pcap is picking up the wrong capture device I'm not sure if its issue with this crate or with pcap_lookupdev

**Comment by Wojtek242** [comment]
Hi, sorry for the late reply. If you're still having this issues could you please reopen the issue (or open a new one), paste the snippet of code that you are using, and the error message you are getting?

**Comment by sigmaSd** [comment]
Hi @Wojtek242 
The issue is `Device::lookup()` selects the wrong device. (Only on windows)

On this list it selects the first one,  while the correct device is the third one.
```
[examples/getdevices.rs:4] &d = [
    Device {
        name: "\\Device\\NPF_{7BBB5BAC-0C03-41BA-93BD-9DB27E66E578}",
        desc: Some(
            "Microsoft",
        ),
    },
    Device {
        name: "\\Device\\NPF_{8EBD8712-179C-4BCA-9D14-A0DF008C2F95}",
        desc: Some(
            "Broadcom NetLink (TM) Gigabit Ethernet Driver",
        ),
    },
    Device {
        name: "\\Device\\NPF_{BA9D402A-D19D-45AA-99DF-2E2A76471B65}",
        desc: Some(
            "Microsoft",
        ),
    },
    Device {
        name: "\\Device\\NPF_{89491F44-14F4-4989-BEFF-64AAC34C2F33}",
        desc: Some(
            "Microsoft",
        ),
    },
]
```

**Comment by Wojtek242** [comment]
Hi, sorry for the late response. I looked into the issue, but didn't actually reply! 

This works according to spec of `libpcap` and this is not a bug per se. https://www.tcpdump.org/manpages/pcap_lookupdev.3pcap.html appears to suggest that it just picks the first available device. Strictly speaking all the `lookup` promises is that the network device is suitable for pcap operations. The device you get is most likely suitable, but not the one you want.

However, it seems we use some obsolete API calls under the hood and they are not documented well enough. I will create an issue and look into it.

**Comment by stappersg** [comment]
On Sun, Jan 24, 2021 at 12:42:18PM -0800, Wojciech Kozlowski wrote:
> However, it seems we use some obsolete API calls under the hood and they
> are not documented well enough. I will create an issue and look into it.

That issue became #158
