### ISSUE TITLE
Can it support full duplex?

### ISSUE THREAD

**Issue by xutianyi1999** [ebfull/pcap#154]
I don’t know the actual operation of npcap or libpcap
If it is supported, I hope the API can operate like this:
```rust
let (rx, tx) = device.open().unwrap();

thread::spawn(move || {
    ......
    tx.sendpacket(...);
});

while let Ok(packet) = rx.next(){
    ......
}
```

**Comment by Wojtek242** [comment]
I believe that it does, but not in the way you show it. `pcap` does not create a separate `tx` and `rx` channel (perhaps there is one within `libpcap` though, but that's out of scope of this crate. Rather, you create a single [`Capture`](https://docs.rs/pcap/0.8.1/pcap/struct.Capture.html), you pick up packets with [`next`](https://docs.rs/pcap/0.8.1/pcap/struct.Capture.html#method.sendpacket), and send packets with [`sendpacket`](https://docs.rs/pcap/0.8.1/pcap/struct.Capture.html#method.sendpacket).

I will close this issue to prevent accumulating stale issues, but do not hesitation to reopen if this does not answer your question!

**Comment by spacemeowx2** [comment]
Same problem here. 

> Rather, you create a single Capture, you pick up packets with next, and send packets with sendpacket.

The problem is the packet can not be sent at anytime. It must wait the `next` return and send the packet.
