### ISSUE TITLE
It seems that I can only get the file traffic

### ISSUE THREAD

**Issue by SWBMESSI** [ebfull/pcap#174]
let dev = Device{
        name:String::from("en0"),
        desc:Some(String::from("NULL")),
    };

    let mut cap = Capture::from_device(dev).unwrap()
                      .open().unwrap();

macOS 11.2.2 (20D80)
![image](https://user-images.githubusercontent.com/29949664/119804673-27ec1800-bf13-11eb-8c44-7d195fe00a42.png)

**Comment by stappersg** [comment]
Please elaborate.
