### ISSUE TITLE
Add support for flush on savefiles

### ISSUE THREAD

**Issue by 3ddi** [ebfull/pcap#177]
I noticed there is an API for that already in libpcap (`pcap_dump_flush`).
I'm using the crate to create pcap files with a certain size limit so I constantly need to check what is the output size on the disk.

I opened a PR to add that functionality

**Comment by Wojtek242** [comment]
Thanks! I've merged it now. CI failed on your PR, but that was due to a new clippy lint which I've just fixed on master so hopefully there won't be any other surprises.
