### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by 3ddi** [ebfull/pcap#181]
Hey,
It has been a while since a new version was released and there are some things that are waiting in the queue. Is there anything specific we are waiting for before bumping the version?

**Comment by 3ddi** [comment]
@Wojtek242 is there anything I can do to help with this one? Do you want me to open a PR for this?

**Comment by Wojtek242** [comment]
Sorry for the late reply - was on holiday in August and I was catching up with work this week.

Yes, bumping the version might be worth it as tokio 1.0 support has been added.

A PR would be helpful if you have the time :)

**Comment by 3ddi** [comment]
No problem, same here :)
Opened a PR for that one, let me know if anything is missing

**Comment by Wojtek242** [comment]
Thanks for the PR. I merged manually as I wanted to make some changes and it was faster this way.

The new version is now live on [`crates.io`](https://crates.io/crates/pcap)
