### ISSUE TITLE
Windows support for `capture-stream` feature

### ISSUE THREAD

**Issue by ColinFinck** [ebfull/pcap#191]
I'm currently using the `pcap-async` crate to perform packet capturing in asynchronous code.
I'm thinking about switching to this crate due to the Windows support via Npcap/WinPcap. But you write that the `capture-stream` feature is only supported on Linux and macOS.

What is the reason for that? Can this be easily fixed?

**Comment by Wojtek242** [comment]
If you look into https://github.com/ebfull/pcap/blob/master/src/stream.rs, you will see that the `capture-stream` relies on `std::os::unix::io::RawFd`. I don't know know how hard this would be to untangle though as I do exactly 0 windows development myself...

If you do try and succeed, feel free to submit a PR!
