### ISSUE TITLE
Safety on returned data

### ISSUE THREAD

**Issue by Will-W** [ebfull/pcap#2]
I think you've got a safety problem with the slice returned from Capture::next(). The pointer returned from pcap_next_ex is only valid until the next call to pcap_next_ex() (or another from that family). The lifetime on the slice you return is only constrained to the lifetime of the Capture object, so I could call next() twice, storing the result of each, and then try and print the first one. At best you'd get junk data, at worst you'd get a segfault.

I've only noticed this because I was building another set of bindings for pcap before I discovered yours, and was curious to see how you were solving that API problem. The only thing I could thing of was to next() take a closure to pass the data to, so the lifetime of the data is only the lifetime of that closure.

**Comment by Will-W** [comment]
I misunderstood the effect of the `&mut self` in the `next()` function so this issue can be ignored. Still learning about lifetimes...

Sorry for the noise!

**Comment by ebfull** [comment]
No problem, I saw your post on reddit too!
