### ISSUE TITLE
Could you please add support to pcap_sendpacket for winpcap?

### ISSUE THREAD

**Issue by ZhangQin3** [ebfull/pcap#21]
Winpcap does export function pcap_sendpacket and I saw the pcap_sendpacket function has been in raw.rs (commented recently), is there a method merging it to the function sendpacket in lib.rs to support sending packets for winpcap?

Thanks.

**Comment by ebfull** [comment]
It's unfortunate that supporting one or the other changes the API, but I guess we have to do it.
