### ISSUE TITLE
Can't find a way to use sendpacket

### ISSUE THREAD

**Issue by k0pernicus** [ebfull/pcap#29]
Hi!
In order to perform my bad knowledge in Network, I'm trying to find all devices connected in my Wifi box with pcap.
To do that, I would to send a broadcast packet from my network device but the function returns to me "Invalid argument", when I send a random data buf.

This is a code example:
```
let data : &[u8] = &[];

let send_data_r = cap.sendpacket(data);
match send_data_r {
     Ok(data) => println!("Data sending... {:?}", data),
     Err(error) => println!("Data sending error... {}", error),
}
```

Anybody here can help me about my request please?

Thanks!

**Comment by ebfull** [comment]
Sending a packet with no contents is probably not valid for any link layer protocol.

**Comment by k0pernicus** [comment]
Oh god, I'm so dumb -_-
Thank you ebfull :-)
Just have to read the pcap documentation to send this package to all wifi devices around...
