### ISSUE TITLE
Documentation error: list_all() seems to be list() now.

### ISSUE THREAD

**Issue by vlttnv** [ebfull/pcap#31]
The page [here](https://ebfull.github.io/pcap/pcap/index.html) suggests that you can use `Device::list_all()` but when you look at the documentation for device you see that it is `list()` instead.

**Comment by ebfull** [comment]
Feel free to submit a PR to fix this and the other documentation error you spotted. If not I'll get around to it over the weekend hopefully.

**Comment by vlttnv** [comment]
No problem. PR should be coming this way tomorrow.

**Comment by vlttnv** [comment]
Quick question: I forked your documentation repo and am editing the HTML manually. I have a feeling there is a better/right way of changing it. If the manual way is OK, then I'll send the pull request.

**Comment by ebfull** [comment]
Oh! All of the documentation is generated using `cargo doc` and so it resides with pcap's source code.

https://github.com/ebfull/pcap/blob/master/src/lib.rs#L17

**Comment by vlttnv** [comment]
Ah OK. Thanks, still learning.

**Comment by vlttnv** [comment]
https://github.com/ebfull/pcap/pull/33
