### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by ebfull** [ebfull/pcap#32]
I think the package changed version or is no longer available.

**Comment by hjr3** [comment]
The travis build seems to be working now. Is there something still to be done?

**Comment by vlttnv** [comment]
I think it is still failing because of `libpcap0.8-dev`
```
Package libpcap0.8-dev is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source

However the following packages replace it:

  libpcap0.8

E: Package 'libpcap0.8-dev' has no installation candidate
```

**Comment by hjr3** [comment]
Oh, I think I ran into this on my project that uses pcap. I will send a PR.

**Comment by hjr3** [comment]
Actually, it looks like the new Ubuntu Precise builds are handling it appropriately. See https://travis-ci.org/ebfull/pcap/builds/111649863

**Comment by ebfull** [comment]
Closing this! :) Thanks.
