### ISSUE TITLE
How to process Packet.data?

### ISSUE THREAD

**Issue by ajvb** [ebfull/pcap#34]
So I started using this library as such:

```Rust
extern crate pcap;

use std::path::Path;

fn main() {
    let p = Path::new("/home/aj/Code/record.cap");
    let result = pcap::Capture::from_file(p);

    let mut cap = match result {
        Ok(capture) => capture,
        Err(err) => panic!("{:?}", err),
    };

    while let Ok(packet) = cap.next() {
        println!("Got packet: {:?}", packet);
    }
}

```

But being a bit of a Rust and Networking noob, I was a little stumped on how to deal with `Packet.data`.

How could I get at the IP or the TCP layer?
How could I extract something like the Seq or Ack from the TCP packet?
How could I get the plaintext of the raw data within a TCP packet?'

I would love any assistance or suggestions on how to deal with the data as provided by this library.

**Comment by ebfull** [comment]
It's actually pretty easy to filter (see the [filter docs](https://ebfull.github.io/pcap/pcap/struct.Capture.html#method.filter)) which gives you a lot of flexibility in terms of packet sniffing certain data, but actually parsing packets is out of scope for this library.

Perhaps [libpnet](https://github.com/libpnet/libpnet) is a better option, but I haven't looked much into it.

**Comment by ebfull** [comment]
Of course, accessing the raw packet contents is simple, as you probably saw already. Closing this.

**Comment by ebfull** [comment]
As a bit of a hint: at one point I was writing gamehacks (hence, this library) and I manually cropped the packets out and wrote parsing routines for their protocol. Wireshark might help you understand the structure of the packets you're intercepting as well.
