### ISSUE TITLE
0.5.3 breaks on windows

### ISSUE THREAD

**Issue by kestein** [ebfull/pcap#38]
When compiling pcap 0.5.3 on my windows 10 64 bit machine, std::os::unix::io::RawFd and std::os::unix::io::AsRawFd throw an error stating that 'unix' could not be found in std::os. Here is the cargo output:

`
C:\.....\.cargo\registry\src\github.com-48ad6e4054423464\pcap-0.5.3\src\lib.rs:62:25: 62:30 error: unresolved import `std::os::unix::io::RawFd`. Could not find `unix` in `std::os` [E0432]
C:\.....\.cargo\registry\src\github.com-48ad6e4054423464\pcap-0.5.3\src\lib.rs:62 use std::os::unix::io::{RawFd, AsRawFd};
                                                                                                                 ^~~~~
C:\.....\.cargo\registry\src\github.com-48ad6e4054423464\pcap-0.5.3\src\lib.rs:62:25: 62:30 help: run `rustc --explain E0432` to see a detailed explanation
C:\.....\.cargo\registry\src\github.com-48ad6e4054423464\pcap-0.5.3\src\lib.rs:62:32: 62:39 error: unresolved import `std::os::unix::io::AsRawFd`. Could not find `unix` in `std::os` [E0432]
C:\.....\.cargo\registry\src\github.com-48ad6e4054423464\pcap-0.5.3\src\lib.rs:62 use std::os::unix::io::{RawFd, AsRawFd};`

**Comment by ebfull** [comment]
Closed by #39
