### ISSUE TITLE
Add support for "dead" captures

### ISSUE THREAD

**Issue by aphistic** [ebfull/pcap#43]
I'm looking to use this library to generate pcap files from data I already have stored in a database but I can't seem to figure out how to do that with the current feature set.  I don't know a lot about pcap but from what I've read it sounds like pcap_open_dead() will open a "fake" pcap_t.  I see the method signature is in src/raw.rs:696 but commented out.  Is that something that can be added or was it excluded for a reason? I could also give it a go if it's something you'd want to add support for.

**Comment by ebfull** [comment]
Can you use the savefile API? https://ebfull.github.io/pcap/pcap/struct.Savefile.html

**Comment by ebfull** [comment]
And https://ebfull.github.io/pcap/pcap/struct.Capture.html#method.from_file

**Comment by aphistic** [comment]
I was hoping to use the Savefile API but when I tried to do a Capture::from_file() it errored out that the file didn't exist, then when I tried creating an empty file first it failed to read the header.  I was also looking to open a device with a random name using Capture::from_device() to get the Savefile but it looks like it requires an actual device for that.  Am I missing something with Capture::from_file()?

**Comment by ebfull** [comment]
`Capture::from_file` will open an already-existing savefile. If you want to write to a savefile (record some network activity into a savefile for later opening, perhaps for analysis or testing) you should use [this API](https://ebfull.github.io/pcap/pcap/struct.Capture.html#method.savefile).

**Comment by aphistic** [comment]
How do I get access to that API without having an existing savefile or a device I want to capture from? In this case I don't want to actively capture from a device (or in theory even have a network device at all), I want to generate a new savefile "manually" by just putting Packets into it without capturing them first.

**Comment by ebfull** [comment]
Yes, good point. We need a way for you to construct a `Savefile` that will be written to disk.

**Comment by aphistic** [comment]
It would be awesome if it could both write to disk and just give you a Vec<u8> of the data too.  In my case it's going to be going directly to a client in a web request.

Do you accept PR's? I could mess around with the pcap_open_dead() to see if it would help?

**Comment by ebfull** [comment]
I do accept PRs. Feel free to give it a shot! :) That sounds like a perfect plan.

**Comment by aphistic** [comment]
I forgot to reference it in the PR, but I just submitted PR #44 for this. Let me know what you think!

**Comment by aphistic** [comment]
Thanks for merging! :)
