### ISSUE TITLE
Why no pcap_set_immediate_mode / pcap_setmintocopy ?

### ISSUE THREAD

**Issue by Darkeye9** [ebfull/pcap#45]
Hi! Congatulations on porting this to Rust, good work!

However as I was scanning your code to decide porting my app to Rust from C++, I was surprised by the absence of these two function calls.
Both of them serve to enable a low latency mode in which pcap/WinPcap reports packets to your application nearly instantly, without buffering them for efficiency.

This of course causes a lot more of context switches, but enables applications to serve as routers, firewalls or something else, where delays introduced by the buffering (Win)pcap  usually does is a pitfall.

I saw that `pcap_set_immediate_mode` is commented out in https://github.com/ebfull/pcap/blob/master/src/raw.rs#L675. Is there a reason for that? Or it was not necessary for you at the time, and decided to leave it out of your lib?

With respect to `pcap_setmintocopy` this is a WinPcap exclusive, as `pcap_set_immediate_mode` is not available in Windows. I don't know if it's simply a substitute or if more complex work is carried out by this function in order to get this feature on windows.

I look forward hearing from you.
Dark_eye

**Comment by ebfull** [comment]
Thanks!

I did not provide support for those functions because I built this library for different purposes. I don't have too much time to add features, but I do take contributions if you need support for this.

**Comment by ryan-robeson** [comment]
Hey, just wanted to say I'm taking a stab at this implementation. I've got it working on OS X 10.9.5 at the moment. I'm going to look into Linux and Windows support.
