### ISSUE TITLE
std::ptr::Unique is marked as unstable and as such cannot be used in the stable release channel

### ISSUE THREAD

**Issue by KieranHunt** [ebfull/pcap#5]
I was compiling your library using rustc 1.1.0 and encountered the following message: 
```
$ cargo build
   Compiling pcap v0.1.3
/Users/kieran/.cargo/registry/src/github.com-1ecc6299db9ec823/pcap-0.1.3/src/lib.rs:1:1: 1:26 error: unstable feature
/Users/kieran/.cargo/registry/src/github.com-1ecc6299db9ec823/pcap-0.1.3/src/lib.rs:1 #![feature(libc, unique)]
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to previous error
Could not compile `pcap`.

To learn more, run the command again with --verbose.
```

Is it your intention to wait until Unique becomes stable? [Looks like they need an RFC to get to that point.](https://github.com/rust-lang/rust/blob/master/src/libcore/ptr.rs#L510) I looked through your code and you seem to use Unique quite a bit so changing it might be irksome.

**Comment by ebfull** [comment]
Thanks, I pulled a limited `Unique` out of std. Now everything should work on stable.
