### ISSUE TITLE
pcap version >0.5.4 broken on Windows

### ISSUE THREAD

**Issue by rigdent** [ebfull/pcap#50]
Hello,
It seems that the functions added between 0.5.4 and 0.5.5, ```pcap_set_tstamp_type``` and ```pcap_set_tstamp_precision```, either don't exist in Windows pcap or have different names. 
For example, when running the example in the docs:
```
extern crate pcap;
use pcap::Device;

fn main() {
    let mut cap = Device::lookup().unwrap().open().unwrap();

    while let Ok(packet) = cap.next() {
        println!("received packet! {:?}", packet);
    }
}
```
You get the following error
```
error: linking with `gcc` failed: exit code: 1
note: C:\Users\IEUser\Documents\hello_world\target\release\deps\libpcap-8479d8f5379e61a2.rlib(pcap-8479d8f5379e61a2.0.o):(.text+0x205c): undefined reference to `pcap_set_tstamp_type'
C:\Users\IEUser\Documents\hello_world\target\release\deps\libpcap-8479d8f5379e61a2.rlib(pcap-8479d8f5379e61a2.0.o):(.text+0x20f2): undefined reference to `pcap_set_tstamp_precision'
ld: C:\Users\IEUser\Documents\hello_world\target\release\deps\libpcap-8479d8f5379e61a2.rlib(pcap-8479d8f5379e61a2.0.o): bad reloc address 0x10 in section `.rdata'
ld: final link failed: Invalid operation
```

This can probably be fixed by making those changes a conditional compilation, but I'm not sure if those  added types should exist for windows as well and something else needs to be done.

I tested with both the latest npcap and win10 pcap on win10 and win7 with the winpcap's wpcap.lib file.

Thanks for taking the time to look at this!

**Comment by ebfull** [comment]
Thanks for the report. I've disabled these on windows until there's another alternative for supporting them. I really dislike the dichotomy between pcap/winpcap.

**Comment by hsluoyz** [comment]
Hi,

I'm the author of [Npcap](https://github.com/nmap/npcap).

This issue is because the libpcap version used by ``Npcap/Win10Pcap/WinPcap`` is too old (a version of 1.0). It doesn't have the mentioned functions.

I'm still waiting for libpcap group to fix the build process on Windows. So that I could work on integrating the latest libpcap 1.7 into Npcap to provide better functions. Thanks!
