### ISSUE TITLE
Automatic libpcap version detection

### ISSUE THREAD

**Issue by aldanor** [ebfull/pcap#68]
Not knowing libpcap version at build time is a major nuisance -- which leads to having to introduce additional features (e.g. in #57, in #66, also mentioned in #55).

Since libpcap provides `pcap_lib_version()`, this problem can be actually solved by having compile-time version detection and all feature flags can be removed, but it will require splitting the crate into *three*. I have done something very similar in [`hdf5-rs`](https://github.com/aldanor/hdf5-rs) crate and it worked out pretty great.

For end-users there's not going to be any negative effect or backwards-incompat, other than not having to specify feature flags.

The way it works is like this.

#### Crate 1: `pcap-lib`

This crate is the one that actually links to `libpcap` and optionally picks up `PCAP_LIBDIR` environment variable. It only imports a single extern function from libpcap: `pcap_lib_version()` and exposes it in safe Rust. It also has an option to generate a set of `#[cfg]` flags based on libpcap version (for example, for version 1.6.0 it may generate pcap_1_6_0, pcap_1_5_0, pcap_1_4_0, pcap_1_3_0, etc, depending how granular we want to be).

([Example](https://github.com/aldanor/hdf5-rs/blob/master/libhdf5-lib/src/lib.rs))

#### Crate 2: `pcap-sys`

This is pretty much what the current `raw` module is. *Except* that it doesn't `#[link]` directly to libpcap; instead, it depends on `pcap-lib` to provide that.

Moreover, it also depends on `pcap-lib`at *build time*, at which point it dumps all version flags; this means that `pcap-sys` now have access to all those `#[cfg]` directives, so we can do stuff like this:

```rust
#[cfg(pcap_1_5_0)]
extern {
    pub fn pcap_fopen_offline_with_tstamp_precision(...);
}
```

([Example: build](https://github.com/aldanor/hdf5-rs/blob/master/libhdf5-sys/build.rs))
([Example: bindings](https://github.com/aldanor/hdf5-rs/blob/master/libhdf5-sys/src/h5p.rs#L572))

#### Crate 3: `pcap`

This is the current crate, less the `raw` module which is now a separate `pcap-sys` and which is a runtime dependency. Besides, the main crate also uses `pcap-lib` at build time in order to get access to version flags, so that we can do

```rust
#[cfg(pcap_1_7_2)]
pub fn savefile_append(...) {}
```

([Example](https://github.com/aldanor/hdf5-rs/blob/master/build.rs))

---- 

@ebfull Would appreciate your opinion on this!

**Comment by ebfull** [comment]
How does this interact with linking, say, when cross compiling to Windows? I originally wrote this library because I needed pcap for something else that I was cross compiling on Linux for Windows, and the versions wouldn't be the same.

**Comment by ebfull** [comment]
Overall I think this is excellent. Let's do it.

**Comment by ebfull** [comment]
I also think that if we break this apart into multiple libraries that we should set up a pcap-rs org on github.

**Comment by aldanor** [comment]
Re: cross-compiling, I don't have much experience with that so I can't really tell, I guess we can try and see... Does cross-compiling on Linux for Windows require having a winpcap dll at build time? Or would it look for Linux libcap while building? How do the build scripts work when cross-compiling? Also, version-wise, I was thinking, we could support specifying an explicit version via `PCAP_LIBVERSION` that would be less or equal than whichever version is detected by `pcap-lib`.

Re: breaking apart, the crates don't necessarily need to be spread across multiple git repos, it should be ok to keep them as folders in the main source tree. That being said, +1 to setting up pcap-rs org regardless :)

Ok, I'll try to put something together soon, but once again, I'm not sure about the cross-compiling part (yet).

**Comment by ebfull** [comment]
Oh, you're right. Let's keep it all in one repository for now then. (We can do the org thing independently.)

**Comment by aldanor** [comment]
I've started collecting some info on libpcap, here's the summary of all versions where the public API changed, and lists of added functions: https://gist.github.com/aldanor/ace2fba5b38a11ef815a730eeb9dde4e

So basically, post-0.8, there's only 5 different versions worth detecting.

**Comment by Wojtek242** [comment]
This discussion is now continued in #118
