### ISSUE TITLE
Support for the MSVC toolchain on Windows

### ISSUE THREAD

**Issue by tzachshabtay** [ebfull/pcap#70]
Hi, is the default toolchain on windows (MSVC) supported?
When using it (on Windows7 64bit), I got: 
```fatal error LNK1181: cannot open input file 'wpcap.lib'```

This happened both with the official installation (WinPCap 4.1) and when I tried to use a pre-compiled dll from VS2008 (from here: https://github.com/patmarion/winpcap/tree/master/Lib/x64).
When I moved to the gnu toolchain it compiled fine, but I'm worried I won't be able to use other libraries as I'm using the not recommended toolchain.

Thanks.

**Comment by aldanor** [comment]
Hi @tzachshabtay, I don't see why it wouldn't work. Could you post more details so it's reproducible? (where's your wpcap.lib located, etc)

@ebfull I think it may be worthy setting up an AppVeyor build alongside Travis, to test both mingw and msvc toolchains? (given that neither of main developers of this crate use windows as a primary os)

**Comment by Trolldemorted** [comment]
Are the build instructions correct?

I got pcap and pnet to run on W10, but i had to download the WinPcap Developer's Pack and add the .lib files to my `LIB` path, otherwise the linker is unable to find them.

Also the instructions don't fit to rustup's workflow, i have to say. Nevertheless, shouldn't moving the libs into `LIB` and the dlls into `PATH` suffice for all usecases?

**Comment by tzachshabtay** [comment]
Hi, sorry, I missed the question when it was originally asked. I didn't have a wpcap.lib, but a wpcap.dll which I placed in the folder as instructed in the readme, both in my rustup toolchains folder (C:\Users\my_user\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib), and I think I also tried using the gnu folder (C:\Users\my_user\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-gnu\lib, this worked when I switched to the gnu toolchain) and also desperately tried to literally put it in the folder you wrote in the readme (C:\Rust\bin\rustlib\x86_64-pc-windows-gnu\lib\). I'm afraid I won't be able to offer more help, the rust experiment in my office was shut down.. :(

**Comment by sekineh** [comment]
Now Windows CI is set up using MSVC toolchain (PR #117).

It also mentions `LIB` environment variable in README which is needed to avoid the following error:
```
fatal error LNK1181: cannot open input file 'wpcap.lib'
```
