### ISSUE TITLE
0.6.0 does not compile on windows

### ISSUE THREAD

**Issue by Trolldemorted** [ebfull/pcap#73]
I added the feature to my .toml as the docu says:

`pcap = { version = "0.5", features = ["pcap-savefile-append"] }`

but cargo complains:

`error: Package pcap v0.5.7 does not have these features: pcap-savefile-append`

Am i doing it wrong, or is this a bug?

W10 64bit
MSVC toolchain
cargo-0.17.0-nightly (f9e5481 2017-03-03)
rustc 1.16.0 (30cf806ef 2017-03-10)

**Comment by Trolldemorted** [comment]
Oh, the feature was introduced in september '16 but the latest release was in april '16.

Could you push a new version to crates.io?

**Comment by ebfull** [comment]
Just pushed `0.6.0`. Thanks!

**Comment by Trolldemorted** [comment]
just tested it, but unfortunately `0.6.0` does not work on windows:

```
C:\Users\XXXXX\.cargo\bin\cargo.exe run
   Compiling pcap v0.6.0
error[E0432]: unresolved import `libc::sockaddr`
 --> C:\Users\XXXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\pcap-0.6.0\src\raw.rs:4:54
  |
4 | use libc::{c_int, c_uint, c_char, c_uchar, c_ushort, sockaddr, timeval, FILE};
  |                                                      ^^^^^^^^ no `sockaddr` in the root

error: aborting due to previous error

error: Could not compile `pcap`.
```

**Comment by ebfull** [comment]
I don't have windows to test on. maybe @aldanor can help? It looks like a libc crate API problem or something.

**Comment by Trolldemorted** [comment]
Unfortunately to them, it is working as intended (https://github.com/rust-lang/libc/commit/c4d4c70a36f82186f259fb6816b0b87997633940, https://github.com/rust-lang/libc/issues/45).

The winapi crate has a definition for sockaddr, but if i [use it](https://github.com/Trolldemorted/pcap/commit/d7bf3d163ed03c4f624ba3bc58c1e36f0432f09f) my programm using pcap crashes with exit code 0xC0000374 (heap corruption).

Why i cannot tell, the sockaddr structs from [libc ](https://github.com/rust-lang/libc/commit/c4d4c70a36f82186f259fb6816b0b87997633940 )and [winapi ](https://docs.rs/winapi/0.1.23/i686-pc-windows-msvc/winapi/ws2def/struct.SOCKADDR.html) look exactly the same to me.

**Comment by sekineh** [comment]
Now Windows CI is working #113 #121 .
