### ISSUE TITLE
Linktype methods cause SEGFAULT

### ISSUE THREAD

**Issue by ericpts** [ebfull/pcap#75]
Due to cstr_to_string assuming ownership of the string.
Fixed in PR #74 .

**Comment by Trolldemorted** [comment]
this was fixed in https://github.com/ebfull/pcap/commit/863ece5e7e222263f8c31f4f856c4141567be0ef, wasn't it?

**Comment by Wojtek242** [comment]
Looks like this is indeed fixed as pointed out. Please reopen if that is not the case.
