### ISSUE TITLE
Add a mechanism for compiling a libpcap filter to a BPF filter

### ISSUE THREAD

**Issue by moosingin3space** [ebfull/pcap#77]
I'd like to be able to use libpcap filter syntax to create a filter for a socket I allocated myself. It would be very helpful if this crate provided a function to construct a BPF filter using `pcap_compile_nopcap`, which would then be usable in a call to `setsockopt` to attach a filter.

**Comment by squeed** [comment]
Working on this. Need ebfull/pcap#91 to be released first, but then we can do this.

**Comment by Wojtek242** [comment]
Closed through #56, #91, and #148
