### ISSUE TITLE
tokio / streamlisten fails with IoError(InvalidInput)

### ISSUE THREAD

**Issue by daschl** [ebfull/pcap#90]
Hi,

I've been trying to run the `streamlisten` example on OSX and it just fails with `IoError(InvalidInput)`.  The `easylisten` example runs through fine. I think this error comes up when the stream is executed, but it's hard to find out what might have caused this.

Happy to provide more info if you let me know what exactly you need :)

**Comment by Wojtek242** [comment]
On the off chance you are still interested, @daschl, the `streamlisten` example has been updated a bit since you last used it so can you try it again. It should print the device (interface) it will be using which might help debugging if you hit this issue again.

If it works, or you just don't care anymore, could you please close the issue? I will close it within a few weeks anyway in case of no response.

**Comment by daschl** [comment]
Thanks for the heads up, right now I do not work on a project but will need in the near future again. In any case let me close it - thanks again!

**Comment by jvns** [comment]
I'm having the same issue: I'm trying to use the stream API on Mac OS and get `IoError(InvalidInput)`.

Here's a small example to reproduce that I made: https://github.com/jvns/pcap-repro/blob/main/src/main.rs (which is basically the same as the streamlisten script, but with less code).

@Wojtek242 do you have any idea where this error might be coming from? I've been trying to grep through the code for `IoError` but I haven't been able to find anything. I can't figure out if the error is coming from the pcap crate or the tokio crate.

I tried to run dtruss to see if there's anything there but everything looks pretty normal to me -- right before it crashes it calls these system calls, which look roughly the same as the system calls that happen when I capture some packets with `tcpdump` (successfully).

```
fcntl(0x6, 0x3, 0x0)		 = 2 0
fcntl(0x6, 0x4, 0x6)		 = 0 0
kevent(0x3, 0x7FFEEE44B3C0, 0x2)		 = 2 0
socket(0x2, 0x2, 0x0)		 = 7 0
ioctl(0x7, 0xC0946990, 0x7FFEEE44BBA0)		 = 0 0
open("/dev/bpf0\0", 0x0, 0x2)		 = -1 Err#16
open("/dev/bpf1\0", 0x0, 0x2)		 = 8 0
ioctl(0x8, 0xC020427D, 0x7FFEEE44BAF0)		 = 0 0
close(0x8)		 = 0 0
ioctl(0x7, 0x80206979, 0x7FFEEE44BB80)		 = 0 0
close(0x7)		 = 0 0
madvise(0x7FCB1AD0A000, 0x80000, 0x9)		 = 0 0
close(0x6)		 = 0 0
```
